# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [59]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np


In [60]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
print df.head()

   admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0


## Part 1. Frequency Tables

#### 1. Let's create a frequency table of our variables

In [61]:
# frequency table for prestige and whether or not someone was admitted
pd.crosstab(index=df['admit'], columns=df['prestige'])

prestige  1.0  2.0  3.0  4.0
admit                       
0          28   95   93   55
1          33   53   28   12

## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

In [62]:
dummy_ranks = pd.get_dummies(df, columns=['prestige'], drop_first=False)

In [63]:
dummy_ranks.head(2)

admit    gre   gpa  prestige_1.0  prestige_2.0  prestige_3.0  prestige_4.0
0      0  380.0  3.61           0.0           0.0           1.0           0.0
1      1  660.0  3.67           0.0           0.0           1.0           0.0

#### 2.2 When modeling our class variables, how many do we need? 



Answer: We need 3 dummy variables for prestige, since there are 4 categories.

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In [64]:
cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_1.0':])
print handCalc.head()

   admit    gre   gpa  prestige_1.0  prestige_2.0  prestige_3.0  prestige_4.0
0      0  380.0  3.61           0.0           0.0           1.0           0.0
1      1  660.0  3.67           0.0           0.0           1.0           0.0
2      1  800.0  4.00           1.0           0.0           0.0           0.0
3      1  640.0  3.19           0.0           0.0           0.0           1.0
4      0  520.0  2.93           0.0           0.0           0.0           1.0


In [65]:
#crosstab prestige 1 admission 
# frequency table cutting prestige and whether or not someone was admitted
pd.crosstab(index=handCalc['admit'], columns=handCalc['prestige_1.0'])

prestige_1.0  0.0  1.0
admit                 
0             243   28
1              93   33

#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked college

In [66]:
handCalc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397 entries, 0 to 399
Data columns (total 7 columns):
admit           397 non-null int64
gre             397 non-null float64
gpa             397 non-null float64
prestige_1.0    397 non-null float64
prestige_2.0    397 non-null float64
prestige_3.0    397 non-null float64
prestige_4.0    397 non-null float64
dtypes: float64(6), int64(1)
memory usage: 24.8 KB


In [67]:
def odds(prob):
    print prob/(1-prob)

probability_rankedone = (33./397)
print odds(probability_rankedone)

0.0906593406593
None


#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

In [68]:
probability_notone = 93./397

print odds(probability_notone)

0.305921052632
None


#### 3.3 Calculate the odds ratio

In [69]:
print np.exp(0.0906593406593)

1.09489595519


#### 3.4 Write this finding in a sentenance: 

Answer: Attending an udergrad school of prestige level 1, increases the odds of being admitted to grad school by about 325%.

#### 3.5 Print the cross tab for prestige_4

In [70]:
pd.crosstab(index=handCalc['admit'], columns=handCalc['prestige_4.0'])

prestige_4.0  0.0  1.0
admit                 
0             216   55
1             114   12

#### 3.6 Calculate the OR 

In [71]:
odds(12./397)

0.0311688311688


In [72]:
print np.exp(0.0311688311688)

1.03165966549


#### 3.7 Write this finding in a sentence

Answer: Attending an udergrad school of prestige level 4, decreases the odds of being admitted to grad school by about 100%.

## Part 4. Analysis

In [73]:
# create a clean data frame for the regression
cols_to_keep = ['admit', 'gre', 'gpa']
data = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_2.0':])
print data.head()

   admit    gre   gpa  prestige_2.0  prestige_3.0  prestige_4.0
0      0  380.0  3.61           0.0           1.0           0.0
1      1  660.0  3.67           0.0           1.0           0.0
2      1  800.0  4.00           0.0           0.0           0.0
3      1  640.0  3.19           0.0           0.0           1.0
4      0  520.0  2.93           0.0           0.0           1.0


We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [74]:
# manually add the intercept
data['intercept'] = 1.0

In [75]:
data.head()

admit    gre   gpa  prestige_2.0  prestige_3.0  prestige_4.0  intercept
0      0  380.0  3.61           0.0           1.0           0.0        1.0
1      1  660.0  3.67           0.0           1.0           0.0        1.0
2      1  800.0  4.00           0.0           0.0           0.0        1.0
3      1  640.0  3.19           0.0           0.0           1.0        1.0
4      0  520.0  2.93           0.0           0.0           1.0        1.0

#### 4.1 Set the covariates to a variable called train_cols

In [76]:
train_cols = data.columns[1:]

#### 4.2 Fit the model

In [77]:
logit = sm.Logit(data['admit'], data[train_cols])
result = logit.fit()

Optimization terminated successfully.
         Current function value: 0.573854
         Iterations 6


#### 4.3 Print the summary results

In [78]:
print result.summary()

                           Logit Regression Results                           
Dep. Variable:                  admit   No. Observations:                  397
Model:                          Logit   Df Residuals:                      391
Method:                           MLE   Df Model:                            5
Date:                Mon, 27 Feb 2017   Pseudo R-squ.:                 0.08166
Time:                        22:34:20   Log-Likelihood:                -227.82
converged:                       True   LL-Null:                       -248.08
                                        LLR p-value:                 1.176e-07
                   coef    std err          z      P>|z|      [95.0% Conf. Int.]
--------------------------------------------------------------------------------
gre              0.0022      0.001      2.028      0.043      7.44e-05     0.004
gpa              0.7793      0.333      2.344      0.019         0.128     1.431
prestige_2.0    -0.6801      0.317     -2.14

#### 4.4 Calculate the odds ratios of the coeffiencents and their 95% CI intervals

hint 1: np.exp(X)

hint 2: conf['OR'] = params
        
           conf.columns = ['2.5%', '97.5%', 'OR']

In [79]:
params = result.params
conf = result.conf_int()
conf['OR'] = params
conf.columns = ['2.5%', '97.5%', 'OR']
print np.exp(conf)

                  2.5%     97.5%        OR
gre           1.000074  1.004372  1.002221
gpa           1.136120  4.183113  2.180027
prestige_2.0  0.272168  0.942767  0.506548
prestige_3.0  0.133377  0.515419  0.262192
prestige_4.0  0.093329  0.479411  0.211525
intercept     0.002207  0.194440  0.020716


#### 4.5 Interpret the OR of Prestige_2

Answer: A student who went to a school of prestige level 2 has about 50% lower odds of being admitted.

#### 4.6 Interpret the OR of GPA

Answer: An increase in GPA of 1, increases the odds of being admitted by about 218%.

## Part 5: Predicted probablities


As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [80]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [102]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(data['gre'].min(), data['gre'].max(), 10)
print gres
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(data['gpa'].min(), data['gpa'].max(), 10)
print gpas
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))

[ 220.          284.44444444  348.88888889  413.33333333  477.77777778
  542.22222222  606.66666667  671.11111111  735.55555556  800.        ]
[ 2.26        2.45333333  2.64666667  2.84        3.03333333  3.22666667
  3.42        3.61333333  3.80666667  4.        ]


In [103]:
combos.info()
combos.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
0    400 non-null float64
1    400 non-null float64
2    400 non-null float64
3    400 non-null float64
dtypes: float64(4)
memory usage: 12.6 KB


0         1    2    3
0  220.0  2.260000  1.0  1.0
1  220.0  2.260000  2.0  1.0
2  220.0  2.260000  3.0  1.0
3  220.0  2.260000  4.0  1.0
4  220.0  2.453333  1.0  1.0

In [104]:
combos.columns = ['gre', 'gpa', 'prestige', 'intercept']

In [105]:
combos.head()

gre       gpa  prestige  intercept
0  220.0  2.260000       1.0        1.0
1  220.0  2.260000       2.0        1.0
2  220.0  2.260000       3.0        1.0
3  220.0  2.260000       4.0        1.0
4  220.0  2.453333       1.0        1.0

#### 5.1 Recreate the dummy variables

In [107]:
# recreate the dummy variables
combos = pd.get_dummies(combos, columns=['prestige'], drop_first=True)
# keep only what we need for making predictions
combos.head()

gre       gpa  intercept  prestige_2.0  prestige_3.0  prestige_4.0
0  220.0  2.260000        1.0           0.0           0.0           0.0
1  220.0  2.260000        1.0           1.0           0.0           0.0
2  220.0  2.260000        1.0           0.0           1.0           0.0
3  220.0  2.260000        1.0           0.0           0.0           1.0
4  220.0  2.453333        1.0           0.0           0.0           0.0

#### 5.2 Make predictions on the enumerated dataset

In [108]:
combos['admit_predict'] = result.predict(combos[train_cols])

#### 5.3 Interpret findings for the last 4 observations

In [112]:
combos.tail(4)

gre  gpa  intercept  prestige_2.0  prestige_3.0  prestige_4.0  \
396  800.0  4.0        1.0           0.0           0.0           0.0   
397  800.0  4.0        1.0           1.0           0.0           0.0   
398  800.0  4.0        1.0           0.0           1.0           0.0   
399  800.0  4.0        1.0           0.0           0.0           1.0   

     admit_predict  
396       0.734040  
397       0.582995  
398       0.419833  
399       0.368608

Answer: When gre and gpa are the same, schools with more prestige have a greater probability of being admitted to grad school.

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.